alias mv='mv -v'
alias cp='cp -v'
alias memcheck='valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes'

export EDITOR=vim
export VISUAL=vim
PS1='\[\e[0;95m\]\u\[\e[0;91m\]@\[\e[0;96m\]\h\[\e[0m\]:\[\e[0m\]\w\[\e[0m\]$\[\e[0m\]'
